### ISSUE TITLE
【Android】-【7.4.9211】【在兆芯zx2800 android 7.1中，退出会议后APP会闪退】

### ISSUE THREAD

**Issue by LauJJ** [tencentyun/TRTCSDK#265]
【当前现象】
是集成官方demo做的测试，发现在兆芯zx2800 android 7.1中，退出会议后，偶尔APP会闪退；

【集成包】
LiteAVSDK_TRTC:latest.release

【SDKAppID】
1400400052

【房间号】
100367

【useID】
deviceapp94D431AA0012

【问题时间段】
2020-07-29 17:00~17:43

【机型】
zx2800 android7.1

【之前版本有无此问题】
有

【复现概率】
偶现

【复现途径】
1，进入会议
2，退出会议

【相关附件】
    --------- beginning of crash
2020-07-29 17:21:13.845 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x240124 in tid 4620 (HWVideoEncoder)
2020-07-29 17:21:13.934 A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-07-29 17:21:13.934 A/DEBUG: Build fingerprint: 'Android/zx2800_general/zx2800_general:7.1.2/N2G48H/markwe06181452:userdebug/dev-keys'
2020-07-29 17:21:13.934 A/DEBUG: Revision: '0'
2020-07-29 17:21:13.934 A/DEBUG: ABI: 'arm'
2020-07-29 17:21:13.935 A/DEBUG: pid: 4135, tid: 4620, name: HWVideoEncoder  >>> com.exechina.ecall_device <<<
2020-07-29 17:21:13.935 A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x240124
2020-07-29 17:21:13.935 A/DEBUG:     r0 00240040  r1 7e703000  r2 00000000  r3 00000000
2020-07-29 17:21:13.935 A/DEBUG:     r4 00000000  r5 00000000  r6 00005310  r7 7e708310
2020-07-29 17:21:13.935 A/DEBUG:     r8 7e708354  r9 0002e860  sl 7e703000  fp 00000001
2020-07-29 17:21:13.935 A/DEBUG:     ip 00000001  sp 84994a18  lr 00000000  pc 8fa4afd4  cpsr 20070030
2020-07-29 17:21:13.937 A/DEBUG: backtrace:
2020-07-29 17:21:13.938 A/DEBUG:     #00 pc 0013bfd4  /system/vendor/lib/egl/libGLESv2_s3g.so (_Z31__glS3EltMapCoreDirtyToEltDirtyP14__GLcontextRec+3355)
2020-07-29 17:21:13.938 A/DEBUG:     #01 pc 000e554b  /system/vendor/lib/egl/libGLESv2_s3g.so (__glEvaluateAttributeChange+2234)
2020-07-29 17:21:13.938 A/DEBUG:     #02 pc 000e62f9  /system/vendor/lib/egl/libGLESv2_s3g.so (__glDrawArrayPrimitive+160)
2020-07-29 17:21:13.938 A/DEBUG:     #03 pc 00103601  /system/vendor/lib/egl/libGLESv2_s3g.so (__glDrawArrays+744)
2020-07-29 17:21:13.938 A/DEBUG:     #04 pc 001037eb  /system/vendor/lib/egl/libGLESv2_s3g.so (__glim_DrawArrays+24)
2020-07-29 17:21:13.938 A/DEBUG:     #05 pc 74112c45  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x2797000)
2020-07-29 17:21:15.307 E/InputDispatcher: channel '4cc8370 com.exechina.ecall_device/com.tencent.liteav.meeting.ui.MeetingMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-07-29 17:21:15.309 E/InputDispatcher: channel '413854b com.exechina.ecall_device/com.exechina.ecall_device.activity.Main2Activity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-07-29 17:21:15.331 E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
2020-07-29 17:21:15.332 E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
2020-07-29 17:21:15.422 E/CameraService: binderDied: Java client's binder died, removing it from the list of active clients
2020-07-29 17:21:16.454 E/CrashReport: --------------------------------------------------------------------------------------------
2020-07-29 17:21:16.454 E/CrashReport: --------------------------------------------------------------------------------------------
2020-07-29 17:21:16.544 E/CrashReport: java.lang.InterruptedException
        at java.lang.Thread.sleep(Native Method)
        at java.lang.Thread.sleep(Thread.java:371)
        at java.lang.Thread.sleep(Thread.java:313)
        at com.tencent.bugly.proguard.as.run(BUGLY:194)
2020-07-29 17:21:16.899 E/TXCAudioEngineJNI: link traeimp-rtmp success !
2020-07-29 17:21:16.902 E/Unknow: [audio_device_android.cpp, AudioDeviceAndroid, 183]:AudioEngine : AudioDeviceAndroid --------------- AudioDeviceAndroid Constructor ---------------
2020-07-29 17:21:16.904 E/TRAE: loadlibrary use org func... 
2020-07-29 17:21:16.910 E/TRAE: [W]TraeAudioManagerLooper start...
2020-07-29 17:21:16.921 E/TRAE: [W]  start used:11ms
2020-07-29 17:21:17.096 E/Unknow: [tx_dr_base.cpp, RecvResponse, 318]:【DR】TCP timeout (4s): Proxy Drop Report
2020-07-29 17:21:17.117 E/LicenceCheck: downloadLicense, mUrl is empty, ignore!
2020-07-29 17:21:17.132 E/Unknow: [TXCMMapFile.cpp, _cleanup, 501]:failed opening file
2020-07-29 17:21:17.133 E/Unknow: [TXCMMapFile.cpp, _cleanup, 501]:failed mapping file
2020-07-29 17:21:17.177 E/TRAE: [W]call_preprocess_media done!
2020-07-29 17:21:17.202 E/Unknow: [audio_device_android.cpp, operator, 1070]:AudioEngine : AudioDeviceAndroid exit SetAudioDeviceVolumeType
2020-07-29 17:21:17.232 E/Unknow: [audio_device_android.cpp, operator, 1262]:AudioEngine : AudioDeviceAndroid TRAE 引擎启动完成~ 
2020-07-29 17:21:17.254 E/imsdk.ConversationManager: msgListeners test addMessageListener this:com.tencent.imsdk.conversation.ConversationManager@18b6d70
2020-07-29 17:22:19.022 E/Unknow: [tx_dr_tcp_channel.cpp, SendPacketsTask, 513]:【DR】Idle time > 60s Close TCP
2020-07-29 17:22:19.023 E/Unknow: [TXCIOListener.cpp, operator, 668]:del event failed|EPOLL_CTL_DEL: fd 72|error:2|info:No such file or directory

**Comment by LauJJ** [comment]
有人处理一下么？

**Comment by yifguan** [comment]
> 有人处理一下么？

你好，我们正在分析，目前来看可能和该开发版的系统修改有关

**Comment by LauJJ** [comment]
@yifguan 你好，能具体一点是哪部分的修改会影响到库的使用吗？

**Comment by jianboy** [comment]
两年了，还未解决
