### ISSUE TITLE
点击+号开始直播异常退出

### ISSUE THREAD

**Issue by qiaoaimi** [tencentyun/TRTCSDK#322]
2020-10-20 12:59:33.383 739-3450/? E/ANDR-PERF-MPCTL: poll() has timed out for /sys/module/msm_performance/events/cpu_hotplug
2020-10-20 12:59:33.383 739-3450/? E/ANDR-PERF-MPCTL: Block on poll()
2020-10-20 12:59:33.417 29102-29102/com.myproject E/MtaSDK: java.lang.ExceptionInInitializerError
        at com.tencent.liteav.audio.impl.TXCAudioEngineJNI.nativeCheckTraeEngine(TXCAudioEngineJNI.java:101)
        at com.tencent.liteav.audio.TXCAudioEngine.CreateInstanceWithoutInitDevice(TXCAudioEngine.java:71)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:331)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:303)
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:40)
        at com.tencent.liteav.liveroom.model.impl.av.trtc.TXTRTCLiveRoom.init(TXTRTCLiveRoom.java:56)
        at com.tencent.liteav.liveroom.model.impl.TRTCLiveRoomImpl.<init>(TRTCLiveRoomImpl.java:154)
        at com.tencent.liteav.liveroom.model.impl.TRTCLiveRoomImpl.sharedInstance(TRTCLiveRoomImpl.java:130)
        at com.tencent.liteav.liveroom.model.TRTCLiveRoom.sharedInstance(TRTCLiveRoom.java:35)
        at com.tencent.liteav.liveroom.ui.anchor.TCBaseAnchorActivity.onCreate(TCBaseAnchorActivity.java:128)
        at com.tencent.liteav.liveroom.ui.anchor.TCCameraAnchorActivity.onCreate(TCCameraAnchorActivity.java:80)
        at android.app.Activity.performCreate(Activity.java:7232)
        at android.app.Activity.performCreate(Activity.java:7221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.liteav.audio.TXEAudioDef" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.XxzsjTV-8NvtdHW-qMoibRWbGqSU6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.XxzsjTV-8NvtdHW-qMoibRWbGqSU6Q==/lib/arm, /data/app/com.XxzsjTV-8NvtdHW-qMoibRWbGqSU6Q==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.liteav.audio.impl.TXCAudioEngineJNI.nativeCacheClassForNative(Native Method)
        at com.tencent.liteav.audio.impl.TXCAudioEngineJNI.<clinit>(TXCAudioEngineJNI.java:23)
        at com.tencent.liteav.audio.impl.TXCAudioEngineJNI.nativeCheckTraeEngine(TXCAudioEngineJNI.java:101) 
        at com.tencent.liteav.audio.TXCAudioEngine.CreateInstanceWithoutInitDevice(TXCAudioEngine.java:71) 
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:331) 
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:303) 
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:40) 
        at com.tencent.liteav.liveroom.model.impl.av.trtc.TXTRTCLiveRoom.init(TXTRTCLiveRoom.java:56) 
        at com.tencent.liteav.liveroom.model.impl.TRTCLiveRoomImpl.<init>(TRTCLiveRoomImpl.java:154) 
        at com.tencent.liteav.liveroom.model.impl.TRTCLiveRoomImpl.sharedInstance(TRTCLiveRoomImpl.java:130) 
        at com.tencent.liteav.liveroom.model.TRTCLiveRoom.sharedInstance(TRTCLiveRoom.java:35) 
        at com.tencent.liteav.liveroom.ui.anchor.TCBaseAnchorActivity.onCreate(TCBaseAnchorActivity.java:128) 
        at com.tencent.liteav.liveroom.ui.anchor.TCCameraAnchorActivity.onCreate(TCCameraAnchorActivity.java:80) 
        at android.app.Activity.performCreate(Activity.java:7232) 
        at android.app.Activity.performCreate(Activity.java:7221) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6878) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
2020-10-20 12:59:34.143 1737-2194/? E/InputDispatcher: channel '83ebdda com.XxzsjTV/com.tencent.liteav.liveroom.ui.liveroomlist.LiveRoomListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-10-20 12:59:34.145 1737-2194/? E/InputDispatcher: channel 'c1701c8 com.XxzsjTV/com.XxzsjTV.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-10-20 12:59:34.193 1737-1883/? E/libprocessgroup: Error encountered killing process cgroup uid 99183 pid 29203: No such file or directory
2020-10-20 12:59:36.291 27093-29751/? E/libc: Access denied finding property "net.dns1"
2020-10-20 12:59:36.387 739-3450/? E/ANDR-PERF-MPCTL: poll() has timed out for /sys/module/msm_performance/events/cpu_hotplug
2020-10-20 12:59:36.387 739-3450/? E/ANDR-PERF-MPCTL: Block on poll()

**Comment by yifguan** [comment]
Hi, 尝试重新rebuild一下工程看是否可行呢？还有请问您依赖的是哪个版本的sdk呢？

**Comment by qiaoaimi** [comment]
最新版sdk，rebuild过也是不行

**Comment by qiaoaimi** [comment]
最新版sdk，rebuild过也是不行
