### ISSUE TITLE
【Android】-【8.9.10355】【onNetworkChange事件会造成app闪退】

### ISSUE THREAD

**Issue by zwb474287221** [tencentyun/TRTCSDK#471]
【当前现象】
onNetworkChange事件会造成app闪退，firebase Crashlytics 捕捉

【集成包】
专业版Professional

【机型】
![image](https://user-images.githubusercontent.com/32866552/127811843-a0e1eef2-521a-4ea0-9000-2790ea1c839b.png)

【之前版本有无此问题】
如8.7.10102之前没有，8.9.10355有

【复现概率】
偶现

【相关附件】

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.tencent.imsdk.common.NetworkInfoCenter@116c1c4
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.tencent.imsdk.manager.BaseManager.onNetworkChange(:16)
       at com.tencent.imsdk.common.NetworkInfoCenter.onNetworkChanged(:208)
       at com.tencent.imsdk.common.NetworkInfoCenter.onReceive(:45)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by zwb474287221** [comment]
看错了是 IMsdk
