### ISSUE TITLE
【Android】SDK用gradle依赖方式集成最新的，之前都好好的，这次更新之后初始化TRTCCloud.sharedInstance报native方法错误，报错信息如下。请尽快解决。

### ISSUE THREAD

**Issue by fushen0** [tencentyun/TRTCSDK#93]
之前是依赖的：com.tencent.liteav:LiteAVSDK_TRTC:latest.release，过了两个星期再来运行代码，进入通话页面初始化TRTCCloud时，报以下错误：
 Process: com.utalk, PID: 28821
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative(Native Method)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.<clinit>(TXCTraeJNI.java:26)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCheckTraeEngine(TXCTraeJNI.java:87)
        at com.tencent.liteav.audio.a.a(TXCAudioEngine.java:40)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:230)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:193)
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:37)
        at com.utalk.activity.chat.TRTCNewActivity.initTRTCSDK(TRTCNewActivity.java:688)
        at com.utalk.activity.chat.TRTCNewActivity.initData(TRTCNewActivity.java:471)
        at com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:108)
        at com.utalk.base.BaseSupportActivity.onCreate(BaseSupportActivity.java:51)
        at android.app.Activity.performCreate(Activity.java:6850)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2818)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2940)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by kuen229** [comment]
这个sdk内部的一个jni函数找不到出错，原因应该是sdk的so由于某些原因加载失败导致。麻烦先清理下工程缓存然后再重新编译，确保使用的是最新的完整SDK。如果还有问题，麻烦把完整的logcat打印log发一下，我们看下是哪里导致so加载失败

**Comment by fushen0** [comment]
我降低版本就可以呢

**Comment by fushen0** [comment]
我降低版本到6.7.7754，之后没报这个错

**Comment by kuen229** [comment]
@fushen0 方便发一下详细log吗？我们详细分析下原因，谢谢

**Comment by fushen0** [comment]
我正在调试，找一个完整的log给你。

**Comment by fushen0** [comment]
现在好像不报这个错了。可能是你说的工程缓存的问题把。

**Comment by kuen229** [comment]
好的，如果后面还碰到这个问题，麻烦再提供完整log我们分析下

**Comment by baohexin** [comment]
我碰到了这个问题：Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)
之前运行好好的，依赖最新版的6.8.7968 implementation 'com.tencent.liteav:LiteAVSDK_TRTC:latest.release'

**Comment by zjyhll** [comment]
说报错为何就没人信呢

**Comment by zjyhll** [comment]
傻狗，把这句话说清楚点，你们卖的产品不收钱的吗
  packagingOptions {
        pickFirst'**/libc++_shared.so'
}

**Comment by kiolygenius** [comment]
arm64-v8a 的 原生so有问题貌似
